import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#121315',
        surface: '#121315',
        'surface-container-lowest': '#0d0e10',
        'surface-container-low': '#1b1c1e',
        'surface-container': '#1f2022',
        'surface-container-high': '#292a2c',
        'surface-container-highest': '#343537',
        'surface-variant': '#343537',
        'surface-bright': '#38393b',
        'graphite-1': '#16181C',
        'graphite-2': '#1D2025',
        primary: '#b4c5ff',
        'on-primary': '#002a77',
        'primary-container': '#608bff',
        'on-primary-container': '#002469',
        'inverse-primary': '#0053da',
        'primary-fixed': '#dbe1ff',
        secondary: '#a9c7ff',
        'on-secondary': '#003063',
        'secondary-container': '#0464c3',
        'on-secondary-container': '#d9e4ff',
        'chrome-lo': '#9AA3AD',
        slate: '#8A8F98',
        'slate-dim': '#5B5F66',
        'border-line': '#26292F',
        outline: '#8d90a1',
        'outline-variant': '#424655',
        'on-surface': '#e3e2e5',
        'on-surface-variant': '#c3c6d8',
        'error': '#ffb4ab',
      },
      fontFamily: {
        sans: ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        display: ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        caption: ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'data-mono': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'label-ui': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'eyebrow-mono': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'micro-mono': ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        'body-md': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        display: ['40px', { lineHeight: '1.2', letterSpacing: '-0.5px', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-ui': ['13px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['19px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '1.3', letterSpacing: '-0.5px', fontWeight: '700' }],
        'eyebrow-mono': ['11px', { lineHeight: '1.2', letterSpacing: '3px', fontWeight: '400' }],
        'micro-mono': ['10px', { lineHeight: '1.2', letterSpacing: '1px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      spacing: {
        'tight-gap': '8px',
        'grid-gutter': '12px',
        'container-max': '1400px',
        'stack-gap': '28px',
        'edge-margin': '32px',
        'section-gap': '56px',
        'component-padding': '20px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      boxShadow: {
        'blue-glow': '0 0 15px rgba(47, 111, 255, 0.25)',
        'header-glow': '0 0 8px rgba(180, 197, 255, 0.3)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

export default config;
